--Insert address on database
INSERT INTO ADDRESS (ID,CITY,POST_CODE,STATE,STREET)
VALUES(1,'Sydney','2121','NSW','Street 1');
INSERT INTO ADDRESS (ID,CITY,POST_CODE,STATE,STREET)
VALUES(2,'Sydney','2020','NSW','Street 2');
INSERT INTO ADDRESS (ID,CITY,POST_CODE,STATE,STREET)
VALUES(3,'Sydney','2030','NSW','Street 3');
INSERT INTO ADDRESS (ID,CITY,POST_CODE,STATE,STREET)
VALUES(4,'Sydney','1234','NSW','Street 4');
INSERT INTO ADDRESS (ID,CITY,POST_CODE,STATE,STREET)
VALUES(5,'Sydney','2222','NSW','Street 5');
INSERT INTO ADDRESS (ID,CITY,POST_CODE,STATE,STREET)
VALUES(6,'Sydney','3333','NSW','Street 6');
INSERT INTO ADDRESS (ID,CITY,POST_CODE,STATE,STREET)
VALUES(7,'Sydney','4444','NSW','Street 7');
INSERT INTO ADDRESS (ID,CITY,POST_CODE,STATE,STREET)
VALUES(8,'Sydney','5555','NSW','Street 8');
INSERT INTO ADDRESS (ID,CITY,POST_CODE,STATE,STREET)
VALUES(9,'Sydney','1123','NSW','Street 9');
INSERT INTO ADDRESS (ID,CITY,POST_CODE,STATE,STREET)
VALUES(10,'Sydney','1234','NSW','Street 10');


--Insert users
INSERT INTO USER_DETAIL (ID,FIRST_NAME,LAST_NAME,GENDER,TITLE,ADDRESS_ID)
VALUES(1,'Marco','Araujo','Male','Mr',1);
INSERT INTO USER_DETAIL (ID,FIRST_NAME,LAST_NAME,GENDER,TITLE,ADDRESS_ID)
VALUES(2,'User','2','Male','Mr',2);
INSERT INTO USER_DETAIL (ID,FIRST_NAME,LAST_NAME,GENDER,TITLE,ADDRESS_ID)
VALUES(3,'User','3','Male','Mr',3);
INSERT INTO USER_DETAIL (ID,FIRST_NAME,LAST_NAME,GENDER,TITLE,ADDRESS_ID)
VALUES(4,'User','4','Male','Mr',4);
INSERT INTO USER_DETAIL (ID,FIRST_NAME,LAST_NAME,GENDER,TITLE,ADDRESS_ID)
VALUES(5,'User','5','Male','Mr',5);
INSERT INTO USER_DETAIL (ID,FIRST_NAME,LAST_NAME,GENDER,TITLE,ADDRESS_ID)
VALUES(6,'User','6','Male','Mr',6);
INSERT INTO USER_DETAIL (ID,FIRST_NAME,LAST_NAME,GENDER,TITLE,ADDRESS_ID)
VALUES(7,'User','7','Male','Mr',7);
INSERT INTO USER_DETAIL (ID,FIRST_NAME,LAST_NAME,GENDER,TITLE,ADDRESS_ID)
VALUES(8,'User','8','Male','Mr',8);
INSERT INTO USER_DETAIL (ID,FIRST_NAME,LAST_NAME,GENDER,TITLE,ADDRESS_ID)
VALUES(9,'User','9','Male','Mr',9);
INSERT INTO USER_DETAIL (ID,FIRST_NAME,LAST_NAME,GENDER,TITLE,ADDRESS_ID)
VALUES(10,'User','10','Male','Mr',10);